name: frontend_flutter
description: Flutter client for FastAPI blockchain chat with MetaMask DID
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  web_socket_channel: ^2.4.5
  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  url_launcher: ^6.3.0
  js: ^0.7.1
  # Optional: add walletconnect for mobile later
  walletconnect_flutter_v2: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - .env